version: '3.8'
services:
  mk-torunaments:
    build: ./
  mongo: 
    image: mongo:7-jammy 
    container_name: docker-mongo
    ports: ['27017:27017'] 
    volumes: [mongo_data:/data/db] 

volumes:
  mongo_data: