version: '3.8'

services:

  mk-tournaments:
    build: ./
    container_name: mk-tournaments
    ports:
      - "5623:5623"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/techcup_tournaments
      SERVER_PORT: 5623
    depends_on:
      - mongo
    restart: on-failure

  mongo:
    image: mongo:7-jammy
    container_name: docker-tournaments
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
