name: Tournament Service - CI (PR to qa)

on:
  pull_request:
    branches:
      - qa

jobs:
  build-test-analyze:
    name: Build, Test & Analyze
    runs-on: ubuntu-latest
    permissions:
      contents: read
    services:
      mongo:
        image: mongo:7-jammy
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.runCommand({ ping: 1 })' --quiet"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 10

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configurar Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: maven

      - name: Cachear paquetes de SonarQube
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Dar permisos al Maven Wrapper
        run: chmod +x mvnw

      - name: Compilar
        run: ./mvnw --batch-mode --no-transfer-progress compile

      - name: Ejecutar pruebas
        env:
          SPRING_DATA_MONGODB_URI: mongodb://localhost:27017/techcup_tournaments
          RABBITMQ_PASS: ${{ secrets.RABBITMQ_PASS }}
        run: ./mvnw --batch-mode --no-transfer-progress test

      - name: Publicar reporte de pruebas
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: target/surefire-reports/
          retention-days: 7

      - name: Análisis estático con SonarQube

        if: success() && github.event.pull_request.head.repo.full_name == github.repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          ./mvnw --batch-mode --no-transfer-progress sonar:sonar \
            -Dsonar.projectKey=TECH-CUP-2026-INT_mk-tournament-service \
            -Dsonar.organization=tech-cup-2026-int \
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
            -Dsonar.token=${{ secrets.SONAR_TOKEN }}

      - name: Empaquetar (jar)
        if: success()
        run: ./mvnw --batch-mode --no-transfer-progress package -DskipTests

      - name: Publicar artefacto JAR
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: tournament-service-jar
          path: target/*.jar
          retention-days: 14